# Generated by Django 4.1.3 on 2022-12-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_tag_alter_customer_email_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
