# Generated by Django 4.1.3 on 2022-12-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_customer_profile_picture_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
